//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

#import "NamaFluttifyPlugin.h"

NS_ASSUME_NONNULL_BEGIN

@interface NamaFluttifyPlugin (SubHandler0)
- (NSDictionary<NSString*, Handler>*) getSubHandler0;
@end

NS_ASSUME_NONNULL_END
