//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

#import "NamaFluttifyPlugin.h"

NS_ASSUME_NONNULL_BEGIN

@interface NamaFluttifyPlugin (SubHandler1)
- (NSDictionary<NSString*, Handler>*) getSubHandler1;
@end

NS_ASSUME_NONNULL_END
