//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

#import "FaceunityNamaFluttifyPlugin.h"

NS_ASSUME_NONNULL_BEGIN

@interface FaceunityNamaFluttifyPlugin (SubHandler1)
- (NSDictionary<NSString*, Handler>*) getSubHandler1;
@end

NS_ASSUME_NONNULL_END
