name: faceunity_nama_fluttify_example
description: Demonstrates how to use the faceunity_nama_fluttify plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  camera: 0.5.7+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  faceunity_nama_fluttify:
    path: ../

flutter:
  uses-material-design: true