name: faceunity_nama_fluttify
description: An `Faceunity Nama(美颜)` Plugin, Powered By `Fluttify`, A Compiler Generating Dart Bindings For Native SDK.
version: 0.0.1
author: yohom <yohombao@qq.com>
homepage: https://fluttify.com

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  foundation_fluttify: ^0.4.16

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.fluttify.faceunity_nama_fluttify
        pluginClass: FaceunityNamaFluttifyPlugin
      ios:
        pluginClass: FaceunityNamaFluttifyPlugin