// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum FUAITYPE {
  FUAITYPE_BACKGROUNDSEGMENTATION,
  FUAITYPE_HAIRSEGMENTATION,
  FUAITYPE_HANDGESTURE,
  FUAITYPE_TONGUETRACKING,
  FUAITYPE_FACELANDMARKS75,
  FUAITYPE_FACELANDMARKS209,
  FUAITYPE_FACELANDMARKS239,
  FUAITYPE_HUMANPOSE2D,
  FUAITYPE_BACKGROUNDSEGMENTATION_GREEN,
  FUAITYPE_FACEPROCESSOR
}