// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:faceunity_nama_fluttify/src/ios/ios.export.g.dart';
import 'package:faceunity_nama_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';

class FUOutput extends NSObject  {
  //region constants
  
  //endregion

  //region creators
  static Future<FUOutput> create__() async {
    final int refId = await MethodChannel('com.fluttify/faceunity_nama_fluttify').invokeMethod('ObjectFactory::createFUOutput');
    final object = FUOutput()..refId = refId..tag = 'faceunity_nama_fluttify';
  
    kNativeObjectPool.add(object);
    return object;
  }
  
  static Future<List<FUOutput>> create_batch__(int length) async {
    if (false) {
      return Future.error('all args must have same length!');
    }
    final List resultBatch = await MethodChannel('com.fluttify/faceunity_nama_fluttify').invokeMethod('ObjectFactory::create_batchFUOutput', {'length': length});
  
    final List<FUOutput> typedResult = resultBatch.map((result) => FUOutput()..refId = result..tag = 'faceunity_nama_fluttify').toList();
    kNativeObjectPool.addAll(typedResult);
    return typedResult;
  }
  
  //endregion

  //region getters
  Future<NSValue/* void* */> get_pixelBuffer() async {
    final result = await MethodChannel('com.fluttify/faceunity_nama_fluttify').invokeMethod("FUOutput::get_pixelBuffer", {'refId': refId});
    kNativeObjectPool.add(NSValue/* void* */()..refId = result..tag = 'faceunity_nama_fluttify');
    return NSValue/* void* */()..refId = result..tag = 'faceunity_nama_fluttify';
  }
  
  //endregion

  //region setters
  Future<void> set_pixelBuffer(NSValue/* void* */ pixelBuffer) async {
    await MethodChannel('com.fluttify/faceunity_nama_fluttify').invokeMethod('FUOutput::set_pixelBuffer', {'refId': refId, "pixelBuffer": pixelBuffer.refId});
  
  
  }
  
  //endregion

  //region methods
  
  //endregion
}

extension FUOutput_Batch on List<FUOutput> {
  //region getters
  Future<List<NSValue/* void* */>> get_pixelBuffer_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/faceunity_nama_fluttify').invokeMethod("FUOutput::get_pixelBuffer_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => NSValue/* void* */()..refId = result..tag = 'faceunity_nama_fluttify').toList();
    kNativeObjectPool.addAll(typedResult);
    return typedResult;
  }
  
  //endregion

  //region setters
  Future<void> set_pixelBuffer_batch(List<NSValue/* void* */> pixelBuffer) async {
    await MethodChannel('com.fluttify/faceunity_nama_fluttify').invokeMethod('FUOutput::set_pixelBuffer_batch', [for (int i = 0; i < this.length; i++) {'refId': this[i].refId, "pixelBuffer": pixelBuffer[i].refId}]);
  
  
  }
  
  //endregion

  //region methods
  
  //endregion
}