// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum FURotationMode {
  FURotationMode0,
  FURotationMode90,
  FURotationMode180,
  FURotationMode270
}